export default {
  "david-quinn": [],
  "dugan-gundelfinger": [],
  "isaac-ravishankar": [],
  "ismael": [],
  "jackie-abraham": [],
  "james-lawes": [],
  "jeremi-durand": [],
  "kate-hollowell": [],
  "leo-zuckerman": [],
  "mapp": [],
  "matt-rhodes": [],
  "matthew-swanson": [],
  "nicolas-heller-aka-new-york-nico": [],
  "nikki-ross": [],
  "nolan-sarner": [],
  "renee-mao": [],
  "rob-fiocca": [],
  "rodney-lucas": [],
  "ruganzu-howard": [],
  "sam-hughes": [],
  "sebastian-hill-esbrand": [],
  "shawn-zeytinoglu": [],
  "stuart-langfield": [],
  "stuart-mcintyre": []
};